name: example-custom-command
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  node-script:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
      - name: Create failed test file
        run: |
          mkdir ${{ github.workspace }}/test-results && echo "should run; needs to run" >> ${{ github.workspace }}/test-results/last-run.txt
      - name: Custom tests 🧪
        uses: cypress-io/github-action@v6
        with:
          command: node testFailed.js run
          working-directory: ${{ github.workspace }}
