name: test-last-failed-node-script
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  node-script:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Output the file contents
        if: always()
        id: step_three
        run: |
          cat ./test-results/last-run.txt
      - name: Custom tests 🧪
        if: always()
        uses: cypress-io/github-action@v6
        with:
          # environment variable used for CI/CD tests in this repo
          env: shouldPass=true
          command: npx cypress-last-failed run
          working-directory: ${{ github.workspace }}
