name: example-custom-command
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6

  node-script:
    needs: cypress-run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Custom tests 🧪
        uses: cypress-io/github-action@v6
        with:
          command: node runFailed.js run
          working-directory: ./
