name: test-last-failed-node-script
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  node-script:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
      - name: Set up test-results directory
        run: mkdir -p test-results/last-run.txt && chmod 777 test-results/last-run.txt
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Display structure of downloaded files
        if: always()
        run: ls -R
      - name: Custom tests 🧪
        if: always()
        uses: cypress-io/github-action@v6
        with:
          command: node testFailed.js run
          working-directory: ${{ github.workspace }}
