name: test-last-failed-node-script
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  node-script:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        id: step_one
        run: npm install
      - name: Run Cypress tests
        id: step_two
        run: |
          npx cypress run
        continue-on-error: true
      - name: Print the value
        id: step_three
        run: |
          printf '%s\n' "$CYPRESS_FAILED_TESTS"
        continue-on-error: true
      - name: Custom tests 🧪
        uses: cypress-io/github-action@v6
        with:
          command: node testFailed.js run
          working-directory: ${{ github.workspace }}
